<?xml version="1.0"?>
<package format="3">
  <name>lynsense_webots_sim</name>
  <version>0.1.0</version>
  <description>Webots smoke-test navigation package for Lynsense.</description>
  <maintainer email="maintainer@rpent.local">RPent</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>rosidl_default_runtime</depend>
  <depend>lynsense_utils</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
